# Generated by Django 5.1.3 on 2024-12-20 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_job', models.CharField(max_length=100)),
                ('Emp_hiredate', models.DateField(auto_now=True)),
                ('Emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Emp_commission', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('Emp_mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
        ),
    ]
